### ISSUE TITLE
Error in signsrch yara rules

### ISSUE THREAD

**Issue by HongThatCong** [kweatherman/yara4ida#2] opened 2022-07-10 15:57 UTC
I am using IDA v7.7.
The Output log is:
>> Yara4Ida: v1.0.0, built Jun 11 2022
Loading rules from: "Z:\IDA\usrdir\plugins\yara4ida_rules\signsrch\signsrch_le.yar"
1,156 rules loaded in 130.9ms

Yara4Ida: Using single threaded scanning.
Walking segments:
 "HEADER", DATA, 10000000 - 10001000, 4 KB
 ".text", CODE, 10001000 - 10008000, 28 KB
 ".rdata", DATA, 10008104 - 1000D000, 19.7 KB
 ".data", DATA, 1000D000 - 1000F000, 8 KB
 ".reloc", DATA, 1000F000 - 10011000, 8 KB

Scanning:
** ConcurrentCallbackGroup::Poll() scanning failed! HR: 0x80004005 "Unspecified error", Total errors: 4 **
Destructing ConcurrentCallbackGroup object.
* Aborted *

Try with another file: signsrch_be.yar, signsrch_le_be.yar, the error is same.

Try with [crypto_signatures.yar](https://github.com/Yara-Rules/rules/blob/master/crypto/crypto_signatures.yar), plugin run OK.

>> Yara4Ida: v1.0.0, built Jun 11 2022
Loading rules from: "C:\Sandbox\crypto_signatures.yar"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 11
 Reason: "string "$c0" may slow down scanning"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 23
 Reason: "string "$c0" may slow down scanning"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 35
 Reason: "string "$c0" may slow down scanning"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 47
 Reason: "string "$c0" may slow down scanning"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 59
 Reason: "string "$c0" may slow down scanning"

 Rule compile WARNING:
 File: "C:\Sandbox\crypto_signatures.yar", line: 71
 Reason: "string "$c0" may slow down scanning"
122 rules loaded in 19.1ms

Yara4Ida: Using single threaded scanning.
Walking segments:
 "HEADER", DATA, 10000000 - 10001000, 4 KB
 ".text", CODE, 10001000 - 10008000, 28 KB
 ".rdata", DATA, 10008104 - 1000D000, 19.7 KB
 ".data", DATA, 1000D000 - 1000F000, 8 KB
 ".reloc", DATA, 1000F000 - 10011000, 8 KB

Scanning:
 [0] "HEADER"
 [1] ".text"
 [2] ".rdata", 1 matches
 [3] ".data"
 [4] ".reloc"

Destructing ConcurrentCallbackGroup object.
Yara4Ida: Found 1 matches in 191.0ms
* Aborted *

The result chooser window showed, but I don't known why "* Aborted *"
My machine, CPU 12 cores.

**Comment by kweatherman** [comment] 2022-07-11 06:09
Cảm ơn, I have seen this before but thought I fixed it; and couldn't reproduce it.
I'll track it down, but in the meantime please use the "Single threaded" checkbox for now.

Incidentally see you have some nice IDA Flirt crypto signatures  on your repo.

**Comment by kweatherman** [comment] 2022-07-17 18:28
Tried for about an hour using various x86 and AMD64, Windows and Linux executables and couldn't get the `** ConcurrentCallbackGroup::Poll() scanning failed! HR: 0x80004005 "Unspecified error", Total errors: 4 **` error to happen.

* Anything unusual about your machine(s) configurations?
* It also errors if you check the "single thread" checkbox?
* IDA Pro 7.7.220218 or other version?

**Comment by kweatherman** [comment] 2022-09-17 10:46
Okay, turns out there was a crash bug having to do with libyara headers in my custom Yara "area" module that I couldn't reproduce at the time and yours was the only report of it.
The exception handler was catching the crash and thus it wasn't being relayed to the user.
Fixed in version [v1.1.0](https://github.com/kweatherman/yara4ida/releases/tag/1.1.0).

Vui lòng thử phiên bản mới. Cảm ơn bạn.

**Closed** 2022-09-27 12:41 UTC
